import VietNamFlag from "./vietnam-flag.png";
import UnitedKingDomFlag from "./united-kingdom-flag.png";
import LogoHeader from "./logo.png";
import EmailIcon from './email-icon.svg';
import SuccessIcon from './success.png';
import ErrorIcon from './error.png';
export { ReactComponent as FacebookIcon } from "./fb.svg";
export { ReactComponent as LinkedinIcon } from "./linkedin.svg";
export { ReactComponent as TwitterIcon } from "./twitter.svg";
export { ReactComponent as InstagramIcon } from "./instagram.svg";
export { VietNamFlag, UnitedKingDomFlag, LogoHeader, EmailIcon, SuccessIcon, ErrorIcon};